---
- name: Playbook to create Execution Environment
  hosts: localhost
  gather_facts: false
  vars:
    ee_aap_version: 2.5
    ee_ah_host: "{{ ee_ah_host }}"
    ee_registry_dest: "{{ ee_registry_dest }}"
    ee_list:
      - name: "{{ ee_name }}"
        image: "{{ base_image }}:latest"
        dependencies:
          ansible_core:
            package_pip: ansible-core==2.16
          ansible_runner:
            package_pip: ansible-runner
          system:
            "{{ system_packages }}"
          python:
            "{{ python_packages }}"
          galaxy:
            collections:
              "{{ galaxy_collections }}"
          exclude:
            system:
              - container-selinux
        options:
          tags: 
            - ee_development:survey
        build_steps:
          prepend_galaxy:
            - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub_certified,upstream_galaxy
            - ENV ANSIBLE_GALAXY_SERVER_UPSTREAM_GALAXY_URL=https://galaxy.ansible.com/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_URL=https://console.redhat.com/api/automation-hub/content/validated/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
            - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_TOKEN

  roles:
    - infra.ee_utilities.ee_builder
