---
- name: Playbook to create Execution Environment
  hosts: localhost
  gather_facts: false
  vars:
    # ee_registry_dest: index.docker.io/r3dact3d
    # ee_registry_username: r3dact3d
    # ee_registry_password:
    # ee_registry_dest: quay.io/brthomps
    # ee_registry_username: brthomps
    ee_ah_host: galaxy.ansible.com
    # ee_ah_token:
    ee_builder_dir_clean: false
    builder_dir: "."
    ee_list:
      - name: netcommon_ee
        tag: 1.1
        base_image: quay.io/ansible/ansible-runner:latest
        builder_image: quay.io/ansible/ansible-builder:latest
        dependencies:
          galaxy:
            collections:
              - ansible.netcommon
          ansible_runner:
            package_pip: ansible-runner
        build_steps:
          prepend_final:
            - RUN whoami
            - RUN cat /etc/os-release
          append_final:
            - RUN echo This is a post-install command!

  # This pre-task section is provided because older environment or
  # environments like build pipelines may not have ansible-builder
  # pre-installed. This is a good place to install other dependencies
  # that need to be in the build pipeline its self not in the final artifact.
  pre_tasks:
    - name: Install ansible-builder
      tags: always
      ansible.builtin.pip:
        name: ansible-builder
        executable: pip3

  roles:
    - infra.ee_utilities.ee_builder
