---
- name: Playbook to create Execution Environment
  hosts: localhost
  gather_facts: false
  vars:
    ee_verbosity: 3
    ee_registry_dest: index.docker.io/r3dact3d
    ee_registry_username: r3dact3d
    ee_pull_collections_from_hub: false
    ee_ah_host: galaxy.ansible.com
    ee_builder_dir_clean: true
    builder_dir: "."
    ee_version: 3
    ee_list:
      - name: ee-builder
        tag: 1.0.7
        base_image: docker.io/redhat/ubi9:latest
        dependencies:
          ansible_core:
            package_pip: ansible-core
          ansible_runner:
            package_pip: ansible-runner
          system:
            - podman
          python:
            - ansible-builder
            - ansible-navigator
          galaxy:
            collections:
              - infra.aap_configuration
              - ansible.hub
              - ansible.eda
              - ansible.controller

        build_steps:
          prepend_galaxy:
            - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub_certified,upstream_galaxy
            - ENV ANSIBLE_GALAXY_SERVER_UPSTREAM_GALAXY_URL=https://galaxy.ansible.com/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_URL=https://console.redhat.com/api/automation-hub/content/validated/
#            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_URL=https://cloud.redhat.com/api/automation-hub/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
            - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_TOKEN

  roles:
    - infra.ee_utilities.ee_builder
