---
- name: Playbook to create Execution Environment
  hosts: localhost
  gather_facts: false
  vars:
    ee_pull_collections_from_hub: false
    ee_ah_host: galaxy.ansible.com
    ee_registry_dest: docker.io/r3dact3d
    ee_registry_username: r3dact3d
    ee_builder_dir_clean: true
    ee_list:
      - name: ee-rhel9-ai
        base_image: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
        dependencies:
          ansible_core:
            package_pip: ansible-core
          ansible_runner:
            package_pip: ansible-runner
          system: []
          python: []
          galaxy:
            collections:
              - redhat.ai 

        build_steps:
          prepend_galaxy:
            - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub_certified,upstream_galaxy
            - ENV ANSIBLE_GALAXY_SERVER_UPSTREAM_GALAXY_URL=https://galaxy.ansible.com/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_URL=https://console.redhat.com/api/automation-hub/content/published/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
            - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_TOKEN

  roles:
    - infra.ee_utilities.ee_builder

