FROM registry.fedoraproject.org/fedora:latest
ARG FLAVOR=stable

# The UID env var should be used in child Containerfile.
ENV UID=1000
ENV GID=0
ENV USERNAME="runner"

# This is to mimic the OpenShift behaviour of adding the dynamic user to group 0.
RUN useradd -G 0 $USERNAME
ENV USER_HOME=/home/${USERNAME}

ARG INSTALL_RPMS="ansible git buildah skopeo unzip podman fuse-overlayfs openssh-clients ucpp python3 python3-pip slirp4netns"
ARG INSTALL_PIP="ansible-navigator ansible-builder ansible-runner"

ENV _CONTAINERS_USERNS_CONFIGURED="" \
    BUILDAH_ISOLATION=chroot

COPY --chown=0:0 entrypoint.sh /

RUN dnf install -y ${INSTALL_RPMS} --exclude container-selinux --skip-unavailable \
    && dnf update -y \
    && dnf clean all \
    && pip3 install ${INSTALL_PIP} \
    && ansible-galaxy collection install infra.ee_utilities
    #
    # Setup for root-less podman
    #
RUN setcap cap_setuid+ep /usr/bin/newuidmap \
    && setcap cap_setgid+ep /usr/bin/newgidmap \
    && touch /etc/subgid /etc/subuid \
    && chown 0:0 /etc/subgid \
    && chown 0:0 /etc/subuid \
    && chown 0:0 /etc/passwd \
    && chown 0:0 /etc/group \
    && chmod +x /entrypoint.sh \
    && chmod -R g=u /etc/passwd /etc/group /etc/subuid /etc/subgid /home

ADD /containers.conf /etc/containers/containers.conf
ADD /podman-containers.conf /home/podman/.config/containers/containers.conf

# Make and set the working directory
RUN mkdir -p ${USER_HOME}/.config/containers \
    && chown -R $USERNAME:$GID $HOME

RUN mkdir -p ${USER_HOME}/.local/share/containers \
    && chown $USERNAME:$GID -R ${USER_HOME} \
    && chmod 644 /etc/containers/containers.conf

# Copy & modify the defaults to provide reference if runtime changes needed.
# Changes here are required for running with fuse-overlay storage inside container.
RUN sed -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /usr/share/containers/storage.conf \
           > /etc/containers/storage.conf

# Note VOLUME options must always happen after the chown call above
# RUN commands can not modify existing volumes
VOLUME /var/lib/containers
VOLUME /home/podman/.local/share/containers

RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers \
    && touch /var/lib/shared/overlay-images/images.lock \
    && touch /var/lib/shared/overlay-layers/layers.lock \
    && touch /var/lib/shared/vfs-images/images.lock \
    && touch /var/lib/shared/vfs-layers/layers.lock

RUN mkdir /runner \
    && chown -R $USERNAME:$GID /runner

WORKDIR /home/runner

USER $USERNAME

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "tail", "-f", "/dev/null" ]



