# .github/workflows/ansible-lint.yml
name: ansible-lint 
on: 
  pull_request:
    branches: ["dev", "test"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
